### ISSUE TITLE
permissions not working

### ISSUE THREAD

**Issue by Dontorpedo** [DigitalCloud/nova-permission-tool#2]
is your documentation missing something? i set roles and permissions, but how do i attach the role to the user?

**Comment by devmtm** [comment]
This is like any nova attach process. Go to view role you want to attach user, and from the users panel, click attach user.

**Comment by Dontorpedo** [comment]
Hi, ok thanks, i did attach the user, after logging in with the login of the user... nothing changes :( can you help me with this?

thank you..
