### ISSUE TITLE
permissions still not working

### ISSUE THREAD

**Issue by Dontorpedo** [DigitalCloud/nova-permission-tool#3]
i did attach the user, after logging in with the login of the user... nothing changes

`model_has_permissions` table is empty after creating permissions...

**Comment by devmtm** [comment]
This tool allow you to add roles and permissions. For more information on how to apply those role and permissions, please, check Authorization guide for Nova:
https://nova.laravel.com/docs/1.0/resources/authorization.html#policies
and for Laravel
https://laravel.com/docs/5.7/authorization
